### PR TITLE
Grouping added

### PR DESCRIPTION
**Pull request by akshaybabloo**
For some reason GitBook deleted the images, but it's still working 🤔

### CODE REVIEW

**Comment by akshaybabloo** [comment]
Any update on this?

**Comment by Fenny** [comment]
Hey @akshaybabloo, the reason I did not merge this PR is because the images were deleted.

Is it possible to re-submit your PR with the changes?

**Comment by akshaybabloo** [comment]
Ya that's weird. GitBook automatically deleted it

**Comment by akshaybabloo** [comment]
@Fenny Added the images back. Can you have a look at it?

**Comment by Fenny** [comment]
Awesome, could you fix the conflicting files?

**Comment by akshaybabloo** [comment]
@Fenny All done

**Comment by akshaybabloo** [comment]
Gentle ping @Fenny

**Comment by Fenny** [comment]
You are awesome <3

**Pull request merged**
