### PR TITLE
Add korean README.md

### PR DESCRIPTION
**Pull request by yhg8423**
I translated README.md of Documentation to Korean.

### CODE REVIEW

**Comment by koddr** [comment]
@yhg8423 thx!

Can you please also send PR with Korean translation to main repo `gofiber/fiber`?
This: https://github.com/gofiber/fiber/blob/master/.github/README_ko.md

**Comment by yhg8423** [comment]
@koddr thank you for your response!

But I am so confused about what should I send PR with Korean translation to main repo `gofiber/fiber`, because README.md in docs and README.md in main repo is different.

Do you mean that should I change README_ko.md in main repo? (ex. "Available in 5 languages" to "Available in 6 languages")

**Comment by koddr** [comment]
@yhg8423 I mean, would be great to re-check Korean translation for main repository. 
That's all I want to say above. 👍

**Comment by yhg8423** [comment]
@koddr oh I see!
I also made a small update to the README_ko.md for main repository 🙂 
Thank you 👍

**Pull request merged**
